export const Users = [
    {
        id: 1,
        profilePicture: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
        username: "Safak Kocaoglu",
    },
    {
        id: 2,
        profilePicture: "https://i.pravatar.cc/250?u=mail@ashallendesign.co.uk",
        username: "Janell Shrum",
    },
    {
        id: 3,
        profilePicture: "https://eu.ui-avatars.com/api/?name=John+Doe&size=250",
        username: "Alex Durden",
    },
    {
        id: 4,
        profilePicture: "https://joeschmoe.io/api/v1/mail@ashallendesign.co.uk",
        username: "Dora Hawks",
    },
    {
        id: 5,
        profilePicture: "https://avatars.dicebear.com/api/adventurer-neutral/mail%40ashallendesign.co.uk.svg",
        username: "Thomas Holden",
    },
    {
        id: 6,
        profilePicture: "https://robohash.org/mail@ashallendesign.co.uk",
        username: "Shirley Beauchamp",
    },
    {
        id: 7,
        profilePicture: "https://via.placeholder.com/250",
        username: "Travis Bennett",
    },
    {
        id: 8,
        profilePicture: "https://baconmockup.com/250/250/",
        username: "Kristen Thomas",
    },
    {
        id: 9,
        profilePicture: "https://www.fillmurray.com/250/250",
        username: "Gary Duty",
    },
    {
        id: 10,
        profilePicture: "http://placekitten.com/250/250",
        username: "Safak Kocaoglu",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "post/2.jpeg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "post/3.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "post/4.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "post/5.jpeg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "post/6.jpeg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "post/7.jpeg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "post/8.jpeg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "post/9.jpeg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];
